[package]
name = "new-nu-parser"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracy-client = { version = "0.19.0", default-features = false } # for tracy v0.14.1
logos = "0.16"
nu-protocol = "0.116"

[profile.profiling]
inherits = "release"
debug = true

[features]
# By default, profiling is disabled. Enable it by the "profile" feature
tracy = [
    "tracy-client/enable",
    "tracy-client/flush-on-exit",
    "tracy-client/sampling",
    "tracy-client/code-transfer",
]

[lib]
name = "new_nu_parser"
path = "src/lib.rs"

[dev-dependencies]
insta = { version = "1.49.0", features = ["glob"] }
tango-bench = "0.8"
nu-parser = "0.116"
nu-cmd-lang = "0.116"

[[bench]]
name = "benchmarks"
harness = false
